### ISSUE TITLE
Java Error when restarting or stopping Server

### ISSUE THREAD

**Issue by Possemaster** [PikaMug/GPS-Quests#1]
Hi Every time I restart or shutdown the server the GPS-Quests plugin states an error.
Since it does not cause any issues so far , i'd like to mention it anyway here.

[13:48:14] [Server thread/INFO]: Stopping server
[13:48:14] [Server thread/INFO]: [GPS-Quests] Disabling GPS-Quests v1.0
[13:48:14] [Server thread/ERROR]: Error occurred while disabling GPS-Quests v1.0 (Is it up to date?)
java.lang.NullPointerException: null
	at com.live.bemmamin.gps.playerdata.PlayerData.getPlayerData(PlayerData.java:88) ~[?:?]
	at com.live.bemmamin.gps.api.GPSAPI.gpsIsActive(GPSAPI.java:159) ~[?:?]
	at me.pikamug.gpsquests.GPSQuests.onDisable(GPSQuests.java:85) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.14.4.jar:git-Paper-196]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:373) ~[patched_1.14.4.jar:git-Paper-196]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:453) ~[patched_1.14.4.jar:git-Paper-196]
	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:439) ~[patched_1.14.4.jar:git-Paper-196]
	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:432) ~[patched_1.14.4.jar:git-Paper-196]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.disablePlugins(CraftServer.java:401) ~[patched_1.14.4.jar:git-Paper-196]
	at net.minecraft.server.v1_14_R1.MinecraftServer.stop(MinecraftServer.java:727) ~[patched_1.14.4.jar:git-Paper-196]
	at net.minecraft.server.v1_14_R1.DedicatedServer.stop(DedicatedServer.java:739) ~[patched_1.14.4.jar:git-Paper-196]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:960) ~[patched_1.14.4.jar:git-Paper-196]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
[13:48:14] [Server thread/INFO]: [Quests] Disabling Quests v3.7.8-b16
[13:48:14] [Server thread/INFO]: [Quests] Saving Quester data.
[13:48:14] [Server thread/INFO]: [CitizensBooks] Disabling CitizensBooks v2.5.2
[13:48:14] [Server thread/INFO]: [MMOItems] Disabling MMOItems v4.7.19b
[13:48:14] [Server thread/INFO]: [Parties] Disabling Parties v2.6.3
[13:48:14] [Server thread/INFO]: [[36mParties[0m] Disabling Parties
[13:48:14] [Server thread/INFO]: [[36mParties[0m] Parties disabled
[13:48:14] [Server thread/INFO]: [Denizen] Disabling Denizen v1.1.0-SNAPSHOT (build 1688-REL)
[13:48:14] [Server thread/INFO]: [Denizen]  v1.1.0-SNAPSHOT (build 1688-REL) disabled.
[13:48:14] [Server thread/INFO]: [EssentialsSpawn] Disabling EssentialsSpawn v2.17.1.17
[13:48:14] [Server thread/INFO]: [gravy] Disabling gravy v1.4.5
[13:48:14] [Server thread/INFO]: [gravy 1.4.5] Gravy Unloaded
[13:48:14] [Server thread/INFO]: [ItemJoin] Disabling ItemJoin v5.0.5-RELEASE-b324
[13:48:14] [Server thread/INFO]: [ItemJoin] has been Disabled.
[13:48:14] [Server thread/INFO]: [TimeIsMoney] Disabling TimeIsMoney v1.9.6.10
[13:48:14] [Server thread/INFO]: [MythicMobs] Disabling MythicMobs v4.6.5-2800
[13:48:14] [Server thread/INFO]: [MythicMobs] Disabling Mythic Mobs...[0m
[13:48:14] [Server thread/INFO]: [MythicMobs] All active settings have been saved.[0m
[13:48:14] [Server thread/INFO]: [MythicMobs] v4.6.5-2800 has been Disabled![0m
[13:48:14] [Server thread/INFO]: [Citizens] Disabling Citizens v2.0.25-SNAPSHOT (build 1732)
[13:48:14] [Server thread/INFO]: [HolographicDisplays] Disabling HolographicDisplays v2.4.1-SNAPSHOT
[13:48:14] [Server thread/INFO]: [BountyHunters] Disabling BountyHunters v2.2.6
[13:48:14] [Server thread/INFO]: [GriefDefender] Disabling GriefDefender v1.2.1
[13:48:14] [Server thread/INFO]: [ChatControl] Disabling ChatControl v8.3.20
[13:48:14] [Server thread/INFO]: [Rankup] Disabling Rankup v3.5.7
[13:48:14] [Server thread/INFO]: [Essentials] Disabling Essentials v2.17.1.17
[13:48:14] [Server thread/INFO]: [Vault] [Vault][Economy] Essentials Economy unhooked.
[13:48:14] [Server thread/INFO]: [GPS] Disabling GPS v2.14.2
[13:48:14] [Server thread/INFO]: [LastLoginAPI] Disabling LastLoginAPI v1.3.0
[13:48:14] [Server thread/INFO]: [[33mLastLoginAPI[0m] Disabling LastLoginAPI
[13:48:14] [Server thread/INFO]: [[33mLastLoginAPI[0m] LastLoginAPI disabled
[13:48:14] [Server thread/INFO]: [PublicCrafters] Disabling PublicCrafters v4.8
[13:48:14] [Server thread/INFO]: [ServerListPlus] Disabling ServerListPlus v3.4.8
[13:48:14] [Server thread/INFO]: [ServerListPlus] ServerListPlus v3.4.8 disabled.
[13:48:14] [Server thread/INFO]: [Vault] Disabling Vault v1.7.2-b107
[13:48:14] [Server thread/INFO]: WEPIF: Vault detected! Using Vault for permissions
[13:48:14] [Server thread/INFO]: [PlaceholderAPI] Unregistered placeholder expansion: vault
[13:48:14] [Server thread/INFO]: [Multiverse-Portals] Disabling Multiverse-Portals v4.1.0-b805
[13:48:14] [Server thread/INFO]: [mcMMO] Disabling mcMMO v2.1.108
[13:48:14] [Server thread/INFO]: [mcMMO] Saving mcMMOPlayers... (0)
[13:48:14] [Server thread/INFO]: [mcMMO] Finished save operation for 0 players!
[13:48:14] [Server thread/INFO]: [RandomTeleport] Disabling RandomTeleport v2.5.1
[13:48:14] [Server thread/INFO]: [Multiverse-Inventories] Disabling Multiverse-Inventories v3.0.0-b459
[13:48:14] [Server thread/INFO]: [Minepacks] Disabling Minepacks v2.0.10-Release
[13:48:15] [Server thread/INFO]: [at.pcgamingfreaks.MinepacksStandalone.libs.com.zaxxer.hikari.HikariDataSource] Minepacks-Connection-Pool - Shutdown initiated...
[13:48:15] [Server thread/INFO]: [at.pcgamingfreaks.MinepacksStandalone.libs.com.zaxxer.hikari.HikariDataSource] Minepacks-Connection-Pool - Shutdown completed.
[13:48:15] [Server thread/INFO]: [Minepacks] [31m Minepacks has been disabled. [33m :( [0m
[13:48:15] [Server thread/INFO]: [Cartographer2] Disabling Cartographer2 v2.9
[13:48:15] [Server thread/INFO]: [ProtocolLib] Disabling ProtocolLib v4.5.0-SNAPSHOT
[13:48:15] [Server thread/INFO]: [Multiverse-Core] Disabling Multiverse-Core v4.1.0-b775
[13:48:15] [Server thread/INFO]: [PlaceholderAPI] Disabling PlaceholderAPI v2.10.4
[13:48:15] [Server thread/INFO]: [VeinMiner] Disabling VeinMiner v1.14.0
[13:48:15] [Server thread/INFO]: [VeinMiner] Clearing localized data
[13:48:15] [Server thread/INFO]: [WorldEdit] Disabling WorldEdit v7.0.1;61bc012
[13:48:15] [Server thread/INFO]: Unregistering com.sk89q.worldedit.bukkit.BukkitServerInterface from WorldEdit
[13:48:15] [Server thread/INFO]: [LuckPerms] Disabling LuckPerms v4.4.30
[13:48:15] [Server thread/INFO]: [LuckPerms] Closing storage...
[13:48:15] [Server thread/INFO]: [LuckPerms] Shutting down internal scheduler...
[13:48:15] [Server thread/INFO]: [LuckPerms] Goodbye!
[13:48:15] [Server thread/INFO]: Saving players
[13:48:15] [Server thread/INFO]: Saving worlds
[13:48:15] [Server thread/INFO]: Saving chunks for level 'wonderworlds'/minecraft:overworld
[13:48:16] [Server thread/INFO]: ThreadedAnvilChunkStorage (wonderworlds): All chunks are saved
[13:48:16] [Server thread/INFO]: Saving chunks for level 'wonderworlds_nether'/minecraft:the_nether
[13:48:16] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[13:48:16] [Server thread/INFO]: Saving chunks for level 'wonderworlds_the_end'/minecraft:the_end
[13:48:16] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[13:48:16] [Server thread/INFO]: ThreadedAnvilChunkStorage (wonderworlds): All chunks are saved
[13:48:16] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[13:48:16] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved

**Comment by PikaMug** [comment]
Thanks for the report. I've pushed a fix which should resolve the issue, available in version 1.1 on SpigotMC.
