### ISSUE TITLE
Could not load 'plugins/GPSQuests-3.0.jar' in 'plugins'

### ISSUE THREAD

**Issue by diskawrs** [PikaMug/GPS-Quests#13]
Papermc 1.20.2 Build 309

[11:23:01 INFO]: Paper: Using OpenSSL 1.1.x (Linux x86_64) cipher from Velocity.
[11:23:01 ERROR]: [ModernPluginLoadingStrategy] Could not load 'plugins/GPSQuests-3.0.jar' in 'plugins'
org.bukkit.plugin.UnknownDependencyException: Unknown/missing dependency plugins: [GPS]. Please download and install these plugins to run 'GPS-Quests'.
        at io.papermc.paper.plugin.entrypoint.strategy.modern.ModernPluginLoadingStrategy.loadProviders(ModernPluginLoadingStrategy.java:82) ~[paper-1.20.2.jar:git-Paper-309]
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:38) ~[paper-1.20.2.jar:git-Paper-309]
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[paper-1.20.2.jar:git-Paper-309]
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.loadPlugins(CraftServer.java:514) ~[paper-1.20.2.jar:git-Paper-309]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:273) ~[paper-1.20.2.jar:git-Paper-309]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1086) ~[paper-1.20.2.jar:git-Paper-309]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-309]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]

**Comment by PikaMug** [comment]
Per the resource description, this plugin requires you have GPS installed. If you already have it, make sure GPS loads correctly at startup.

**Comment by diskawrs** [comment]
Sorry noticed it after posting. Stupid me.
