### ISSUE TITLE
GPS-Quests error on GPS restart and on respawn, GPS-Quests 1.4

### ISSUE THREAD

**Issue by Nakitama** [PikaMug/GPS-Quests#7]
**Quests version:** 3.6.7-b736
**GPS-Quests version:** 1.4
**GPS version:** 2.19.4

If a player retries, restarts, or if the quest is even reset, on a quest with a GPS objective, it will not update the GPS. I believe this will also break quest progress.

```yml
[22:50:31 WARN]: java.lang.IllegalArgumentException: A point with the name 'quests-f75ca28d-5460-4378-a64b-ccc99dbd6eaa1' already exists!
[22:50:31 WARN]:        at com.live.bemmamin.gps.api.GPSAPI.addPoint(GPSAPI.java:38)
[22:50:31 WARN]:        at me.blackvein.quests.Quest.updateGPS(Quest.java:304)
[22:50:31 WARN]:        at me.blackvein.quests.Quester.takeQuest(Quester.java:516)
[22:50:31 WARN]:        at me.blackvein.quests.Quests$QuestPrompt.acceptInput(Quests.java:370)
[22:50:31 WARN]:        at org.bukkit.conversations.Conversation.acceptInput(Conversation.java:228)
[22:50:31 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.conversations.ConversationTracker.acceptConversationInput(ConversationTracker.java:60)
[22:50:31 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.entity.CraftPlayer.acceptConversationInput(CraftPlayer.java:1118)
[22:50:31 WARN]:        at net.minecraft.server.v1_12_R1.PlayerConnection$5.evaluate(PlayerConnection.java:1248)
[22:50:31 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.util.Waitable.run(Waitable.java:24)
[22:50:31 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:758)
[22:50:31 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
[22:50:31 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[22:50:31 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[22:50:31 WARN]:        at java.base/java.lang.Thread.run(Unknown Source)
```

Whenever a player dies, it will trigger an error in console for whatever reason.
```yml
[22:54:24 ERROR]: Could not pass event PlayerRespawnEvent to GPS-Quests v1.4
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[craftbukkit.jar:git-Spigot-dcd1643-e60fc34]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit.jar:git-Spigot-dcd1643-e60fc34]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [craftbukkit.jar:git-Spigot-dcd1643-e60fc34]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [craftbukkit.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.PlayerList.moveToWorld(PlayerList.java:654) [craftbukkit.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.PlayerList.moveToWorld(PlayerList.java:582) [craftbukkit.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1653) [craftbukkit.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.PacketPlayInClientCommand.a(SourceFile:31) [craftbukkit.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.PacketPlayInClientCommand.a(SourceFile:8) [craftbukkit.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [craftbukkit.jar:git-Spigot-dcd1643-e60fc34]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [craftbukkit.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [craftbukkit.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [craftbukkit.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [craftbukkit.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [craftbukkit.jar:git-Spigot-dcd1643-e60fc34]
        at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.NoSuchMethodError: 'me.blackvein.quests.Quest me.blackvein.quests.Quester.getCompassTarget()'
        at me.pikamug.gpsquests.GPSQuests$ServerListener.onPlayerRespawnEvent(GPSQuests.java:133) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[craftbukkit.jar:git-Spigot-dcd1643-e60fc34]
        ... 17 more
        ```

**Comment by PikaMug** [comment]
For future readers, the solution is to update to the latest version of Quests.

**Comment by Nakitama** [comment]
Yep, just an odd mismatch of plugins, which is why I closed it. :)
